[build-system]
requires = [
    "setuptools",
    "scikit-build",
    "wheel",
    "cmake",
    "pybind11",
    "eigen",
    "numpy",
    "scipy",
    "pyyaml",
]

[tool.flake8]
max-line-length = 88
extend-ignore = "E203,W503"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
